[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
async-task = { version = "4.7", default-features = false }
bitflags = "1.3.2"
bitvec-rs = "0.2"
buddy_system_allocator = "0.9"
downcast-rs = { version = "1.2", default-features = false }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
log = "0.4"
riscv = "0.10"
sbi-spec = "0.0.6"
spin = "0.9"
unwinding = { version = "0.2", default-features = false, features = ["unwinder", "fde-static", "personality", "panic"] }

[features]
board_qemu = []
board_fu740 = []
error = []
warn = []
info = []
debug = []
trace = []

default = ["info"]
