[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv = { path = "../vendor/riscv/riscv" }
async-task = { version = "4.7", default-features = false }
async-trait = "0.1"
bitflags = "1.3.2"
bitvec-rs = "0.2"
buddy_system_allocator = "0.9"
bytemuck = "1.14"
downcast-rs = { version = "1.2", default-features = false }
futures = { version = "0.3", default-features = false }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
log = "0.4"
lru = "0.12"
num_enum = { version = "0.7.2", default-features = false }
time = { version = "0.3", default-features = false }
sbi-spec = "0.0.6"
spin = "0.9"
unwinding = { version = "0.2", default-features = false, features = ["unwinder", "fde-static", "personality", "panic"] }
xmas-elf = "0.7.0"
virtio-drivers = "0.6.0"

[features]
board_qemu = []
board_fu740 = []
error = []
warn = []
info = []
debug = []
trace = []
strace = []

default = ["strace"]
