use crate::arch::PAGE_SIZE;

pub const KERNEL_PADDR_BASE: usize = 0x80200000;
pub const KERNEL_VADDR_BASE: usize = 0xFFFFFFFF80000000;

pub const KERNEL_ADDR_OFFSET: usize = KERNEL_VADDR_BASE - KERNEL_PADDR_BASE;
